//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NosCore.Networking.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NosCore.Networking.Resource.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {RemoteAddress} blocked by spam filter.
        /// </summary>
        public static string BLOCKED_BY_SPAM_FILTER {
            get {
                return ResourceManager.GetString("BLOCKED_BY_SPAM_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New client connected. ClientId = {0}.
        /// </summary>
        public static string CLIENT_CONNECTED {
            get {
                return ResourceManager.GetString("CLIENT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted packet received: {0} - {1}.
        /// </summary>
        public static string CORRUPTED_PACKET {
            get {
                return ResourceManager.GetString("CORRUPTED_PACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Error: {0}.
        /// </summary>
        public static string ENCODE_ERROR {
            get {
                return ResourceManager.GetString("ENCODE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding error {0}.
        /// </summary>
        public static string ERROR_DECODING {
            get {
                return ResourceManager.GetString("ERROR_DECODING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session ID: {0}.
        /// </summary>
        public static string ERROR_SESSIONID {
            get {
                return ResourceManager.GetString("ERROR_SESSIONID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced disconnection of the client {0}..
        /// </summary>
        public static string FORCED_DISCONNECTION {
            get {
                return ResourceManager.GetString("FORCED_DISCONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening Port {0}.
        /// </summary>
        public static string LISTENING_PORT {
            get {
                return ResourceManager.GetString("LISTENING_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending an invalid packet: {PacketHeader} {ValidationResult}.
        /// </summary>
        public static string SENDING_INVALID_PACKET {
            get {
                return ResourceManager.GetString("SENDING_INVALID_PACKET", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to broadcast to session {0}.
        /// </summary>
        public static string BROADCAST_ERROR {
            get {
                return ResourceManager.GetString("BROADCAST_ERROR", resourceCulture);
            }
        }
    }
}
